---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: safespace
  name: safespacebot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bot
  template:
    metadata:
      labels:
        app: bot
    spec:
      containers:
      - image: jhueppauff/discord-safespacebot@sha256:c397739d97d875e8f83931dd2f8475a3de833f4bd0e6fcde044fdb5a84400c9e
        name: safespacebot
        imagePullPolicy: "Always"
        env:
          - name: BOT_TOKEN
            valueFrom:
              secretKeyRef:
                name: safespacebot
                key: bot_token
          - name: COGNITIVE_SERVICES_APIKEY
            valueFrom:
              secretKeyRef:
                name: safespacebot
                key: cognitive_services_apikey
          - name: COGNITIVE_SERVICES_ENDPOINT
            valueFrom:
              secretKeyRef:
                name: safespacebot
                key: cognitive_services_endpoint
          - name: COGNITIVE_SERVICES_LANGUAGE
            valueFrom:
              secretKeyRef:
                name: safespacebot
                key: cognitive_services_language
          - name: COGNITIVE_SERVICES_REGION
            valueFrom:
              secretKeyRef:
                name: safespacebot
                key: cognitive_services_region
