---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: safespace
  name: safespacebot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bot
  template:
    metadata:
      labels:
        app: bot
    spec:
      containers:
      - image: jhueppauff/discord-safespacebot@sha256:39d67aa5f2b3c2be296896f4929b90c7eccc119b5c29098503879a38d6a45007
        name: safespacebot
        imagePullPolicy: "Always"
        env:
          - name: BOT_TOKEN
            valueFrom:
              secretKeyRef:
                name: safespacebot
                key: bot_token
