---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: safespace
  name: safespacebot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bot
  template:
    metadata:
      labels:
        app: bot
    spec:
      containers:
      - image: jhueppauff/discord-safespacebot@sha256:e312ca67e2e1fe45b36567143605f5e9c281f585d07f9a7e69aa206d0dffa74b
        name: safespacebot
        imagePullPolicy: "Always"
        env:
          - name: BOT_TOKEN
            valueFrom:
              secretKeyRef:
                name: safespacebot
                key: bot_token
